package schema

// Code generated by scripts/gen_field_presence.py. DO NOT EDIT.
//
// Source: https://github.com/google/transit, gtfs/spec/en/reference.md
//
// Which fields a file may carry, and whether the spec requires,
// recommends or merely permits each one. Generated because these are
// facts about the specification rather than judgements about a feed:
// kept by hand they drift, and a validator that reports a field the
// spec calls Optional is stating an opinion under a canonical code's
// name.

// FieldPresence is the spec's Presence column.
type FieldPresence int

const (
	PresenceRequired FieldPresence = iota
	PresenceRecommended
	PresenceOptional
	// PresenceConditionallyRequired and PresenceConditionallyForbidden
	// depend on the rest of the feed, so no generic check can decide
	// them. Each belongs to a rule that knows the condition.
	PresenceConditionallyRequired
	PresenceConditionallyForbidden
)

// fieldPresenceByFile maps each file to its fields and their presence.
var fieldPresenceByFile = map[string]map[string]FieldPresence{
	"agency.txt": {
		"agency_id":       PresenceConditionallyRequired,
		"agency_name":     PresenceRequired,
		"agency_url":      PresenceRequired,
		"agency_timezone": PresenceRequired,
		"agency_lang":     PresenceOptional,
		"agency_phone":    PresenceOptional,
		"agency_fare_url": PresenceOptional,
		"agency_email":    PresenceOptional,
		"cemv_support":    PresenceOptional,
	},
	"areas.txt": {
		"area_id":   PresenceRequired,
		"area_name": PresenceOptional,
	},
	"attributions.txt": {
		"attribution_id":    PresenceOptional,
		"agency_id":         PresenceOptional,
		"route_id":          PresenceOptional,
		"trip_id":           PresenceOptional,
		"organization_name": PresenceRequired,
		"is_producer":       PresenceOptional,
		"is_operator":       PresenceOptional,
		"is_authority":      PresenceOptional,
		"attribution_url":   PresenceOptional,
		"attribution_email": PresenceOptional,
		"attribution_phone": PresenceOptional,
	},
	"booking_rules.txt": {
		"booking_rule_id":           PresenceRequired,
		"booking_type":              PresenceRequired,
		"prior_notice_duration_min": PresenceConditionallyRequired,
		"prior_notice_duration_max": PresenceConditionallyForbidden,
		"prior_notice_last_day":     PresenceConditionallyRequired,
		"prior_notice_last_time":    PresenceConditionallyRequired,
		"prior_notice_start_day":    PresenceConditionallyForbidden,
		"prior_notice_start_time":   PresenceConditionallyRequired,
		"prior_notice_service_id":   PresenceConditionallyForbidden,
		"message":                   PresenceOptional,
		"pickup_message":            PresenceOptional,
		"drop_off_message":          PresenceOptional,
		"phone_number":              PresenceOptional,
		"info_url":                  PresenceOptional,
		"booking_url":               PresenceOptional,
	},
	"calendar.txt": {
		"service_id": PresenceRequired,
		"monday":     PresenceRequired,
		"tuesday":    PresenceRequired,
		"wednesday":  PresenceRequired,
		"thursday":   PresenceRequired,
		"friday":     PresenceRequired,
		"saturday":   PresenceRequired,
		"sunday":     PresenceRequired,
		"start_date": PresenceRequired,
		"end_date":   PresenceRequired,
	},
	"calendar_dates.txt": {
		"service_id":     PresenceRequired,
		"date":           PresenceRequired,
		"exception_type": PresenceRequired,
	},
	"fare_attributes.txt": {
		"fare_id":           PresenceRequired,
		"price":             PresenceRequired,
		"currency_type":     PresenceRequired,
		"payment_method":    PresenceRequired,
		"transfers":         PresenceRequired,
		"agency_id":         PresenceConditionallyRequired,
		"transfer_duration": PresenceOptional,
	},
	"fare_leg_join_rules.txt": {
		"from_network_id": PresenceRequired,
		"to_network_id":   PresenceRequired,
		"from_stop_id":    PresenceConditionallyRequired,
		"to_stop_id":      PresenceConditionallyRequired,
	},
	"fare_leg_rules.txt": {
		"leg_group_id":            PresenceOptional,
		"network_id":              PresenceOptional,
		"from_area_id":            PresenceOptional,
		"to_area_id":              PresenceOptional,
		"from_timeframe_group_id": PresenceOptional,
		"to_timeframe_group_id":   PresenceOptional,
		"fare_product_id":         PresenceRequired,
		"rule_priority":           PresenceOptional,
	},
	"fare_media.txt": {
		"fare_media_id":   PresenceRequired,
		"fare_media_name": PresenceOptional,
		"fare_media_type": PresenceRequired,
	},
	"fare_products.txt": {
		"fare_product_id":   PresenceRequired,
		"fare_product_name": PresenceOptional,
		"rider_category_id": PresenceOptional,
		"fare_media_id":     PresenceOptional,
		"amount":            PresenceRequired,
		"currency":          PresenceRequired,
	},
	"fare_rules.txt": {
		"fare_id":        PresenceRequired,
		"route_id":       PresenceOptional,
		"origin_id":      PresenceOptional,
		"destination_id": PresenceOptional,
		"contains_id":    PresenceOptional,
	},
	"fare_transfer_rules.txt": {
		"from_leg_group_id":   PresenceOptional,
		"to_leg_group_id":     PresenceOptional,
		"transfer_count":      PresenceConditionallyForbidden,
		"duration_limit":      PresenceOptional,
		"duration_limit_type": PresenceConditionallyRequired,
		"fare_transfer_type":  PresenceRequired,
		"fare_product_id":     PresenceOptional,
	},
	"feed_info.txt": {
		"feed_publisher_name": PresenceRequired,
		"feed_publisher_url":  PresenceRequired,
		"feed_lang":           PresenceRequired,
		"default_lang":        PresenceOptional,
		"feed_start_date":     PresenceRecommended,
		"feed_end_date":       PresenceRecommended,
		"feed_version":        PresenceRecommended,
		"feed_contact_email":  PresenceOptional,
		"feed_contact_url":    PresenceOptional,
	},
	"frequencies.txt": {
		"trip_id":      PresenceRequired,
		"start_time":   PresenceRequired,
		"end_time":     PresenceRequired,
		"headway_secs": PresenceRequired,
		"exact_times":  PresenceOptional,
	},
	"levels.txt": {
		"level_id":    PresenceRequired,
		"level_index": PresenceRequired,
		"level_name":  PresenceOptional,
	},
	"location_group_stops.txt": {
		"location_group_id": PresenceRequired,
		"stop_id":           PresenceRequired,
	},
	"location_groups.txt": {
		"location_group_id":   PresenceRequired,
		"location_group_name": PresenceOptional,
	},
	"networks.txt": {
		"network_id":   PresenceRequired,
		"network_name": PresenceOptional,
	},
	"pathways.txt": {
		"pathway_id":             PresenceRequired,
		"from_stop_id":           PresenceRequired,
		"to_stop_id":             PresenceRequired,
		"pathway_mode":           PresenceRequired,
		"is_bidirectional":       PresenceRequired,
		"length":                 PresenceOptional,
		"traversal_time":         PresenceOptional,
		"stair_count":            PresenceOptional,
		"max_slope":              PresenceOptional,
		"min_width":              PresenceOptional,
		"signposted_as":          PresenceOptional,
		"reversed_signposted_as": PresenceOptional,
	},
	"rider_categories.txt": {
		"rider_category_id":        PresenceRequired,
		"rider_category_name":      PresenceRequired,
		"is_default_fare_category": PresenceRequired,
		"eligibility_url":          PresenceOptional,
	},
	"route_networks.txt": {
		"network_id": PresenceRequired,
		"route_id":   PresenceRequired,
	},
	"routes.txt": {
		"route_id":            PresenceRequired,
		"agency_id":           PresenceConditionallyRequired,
		"route_short_name":    PresenceConditionallyRequired,
		"route_long_name":     PresenceConditionallyRequired,
		"route_desc":          PresenceOptional,
		"route_type":          PresenceRequired,
		"route_url":           PresenceOptional,
		"route_color":         PresenceOptional,
		"route_text_color":    PresenceOptional,
		"route_sort_order":    PresenceOptional,
		"continuous_pickup":   PresenceConditionallyForbidden,
		"continuous_drop_off": PresenceConditionallyForbidden,
		"network_id":          PresenceConditionallyForbidden,
		"cemv_support":        PresenceOptional,
	},
	"shapes.txt": {
		"shape_id":            PresenceRequired,
		"shape_pt_lat":        PresenceRequired,
		"shape_pt_lon":        PresenceRequired,
		"shape_pt_sequence":   PresenceRequired,
		"shape_dist_traveled": PresenceOptional,
	},
	"stop_areas.txt": {
		"area_id": PresenceRequired,
		"stop_id": PresenceRequired,
	},
	"stop_times.txt": {
		"trip_id":                      PresenceRequired,
		"arrival_time":                 PresenceConditionallyRequired,
		"departure_time":               PresenceConditionallyRequired,
		"stop_id":                      PresenceConditionallyRequired,
		"location_group_id":            PresenceConditionallyForbidden,
		"location_id":                  PresenceConditionallyForbidden,
		"stop_sequence":                PresenceRequired,
		"stop_headsign":                PresenceOptional,
		"start_pickup_drop_off_window": PresenceConditionallyRequired,
		"end_pickup_drop_off_window":   PresenceConditionallyRequired,
		"pickup_type":                  PresenceConditionallyForbidden,
		"drop_off_type":                PresenceConditionallyForbidden,
		"continuous_pickup":            PresenceConditionallyForbidden,
		"continuous_drop_off":          PresenceConditionallyForbidden,
		"shape_dist_traveled":          PresenceOptional,
		"timepoint":                    PresenceOptional,
		"pickup_booking_rule_id":       PresenceOptional,
		"drop_off_booking_rule_id":     PresenceOptional,
	},
	"stops.txt": {
		"stop_id":             PresenceRequired,
		"stop_code":           PresenceOptional,
		"stop_name":           PresenceConditionallyRequired,
		"tts_stop_name":       PresenceOptional,
		"stop_desc":           PresenceOptional,
		"stop_lat":            PresenceConditionallyRequired,
		"stop_lon":            PresenceConditionallyRequired,
		"zone_id":             PresenceOptional,
		"stop_url":            PresenceOptional,
		"location_type":       PresenceOptional,
		"parent_station":      PresenceConditionallyRequired,
		"stop_timezone":       PresenceOptional,
		"wheelchair_boarding": PresenceOptional,
		"level_id":            PresenceOptional,
		"platform_code":       PresenceOptional,
		"stop_access":         PresenceConditionallyForbidden,
	},
	"timeframes.txt": {
		"timeframe_group_id": PresenceRequired,
		"start_time":         PresenceConditionallyRequired,
		"end_time":           PresenceConditionallyRequired,
		"service_id":         PresenceRequired,
	},
	"transfers.txt": {
		"from_stop_id":      PresenceConditionallyRequired,
		"to_stop_id":        PresenceConditionallyRequired,
		"from_route_id":     PresenceOptional,
		"to_route_id":       PresenceOptional,
		"from_trip_id":      PresenceConditionallyRequired,
		"to_trip_id":        PresenceConditionallyRequired,
		"transfer_type":     PresenceRequired,
		"min_transfer_time": PresenceOptional,
	},
	"translations.txt": {
		"table_name":    PresenceRequired,
		"field_name":    PresenceRequired,
		"language":      PresenceRequired,
		"translation":   PresenceRequired,
		"record_id":     PresenceConditionallyRequired,
		"record_sub_id": PresenceConditionallyRequired,
		"field_value":   PresenceConditionallyRequired,
	},
	"trips.txt": {
		"route_id":              PresenceRequired,
		"service_id":            PresenceRequired,
		"trip_id":               PresenceRequired,
		"trip_headsign":         PresenceOptional,
		"trip_short_name":       PresenceOptional,
		"direction_id":          PresenceOptional,
		"block_id":              PresenceOptional,
		"shape_id":              PresenceConditionallyRequired,
		"wheelchair_accessible": PresenceOptional,
		"bikes_allowed":         PresenceOptional,
		"cars_allowed":          PresenceOptional,
		"safe_duration_factor":  PresenceOptional,
		"safe_duration_offset":  PresenceOptional,
	},
}

// FieldsWithPresence returns the fields of a file at a given presence,
// and whether the file is one the spec describes at all.
func FieldsWithPresence(filename string, presence FieldPresence) ([]string, bool) {
	fields, known := fieldPresenceByFile[filename]
	if !known {
		return nil, false
	}
	matching := make([]string, 0, len(fields))
	for field, actual := range fields {
		if actual == presence {
			matching = append(matching, field)
		}
	}
	return matching, true
}

// emptyIsMeaningful lists the Required fields whose value list offers
// "empty" as a choice. Required there means the column must exist, not
// that every row must fill it, so a blank is not a missing value.
var emptyIsMeaningful = map[string]map[string]bool{
	"fare_attributes.txt": {
		"transfers": true,
	},
	"rider_categories.txt": {
		"is_default_fare_category": true,
	},
	"transfers.txt": {
		"transfer_type": true,
	},
}

// EmptyIsMeaningful reports whether a blank in this field is a value
// rather than an omission.
func EmptyIsMeaningful(filename string, field string) bool {
	return emptyIsMeaningful[filename][field]
}

// KnownColumns returns every column the spec defines for a file, and
// whether the file is described at all.
func KnownColumns(filename string) ([]string, bool) {
	fields, known := fieldPresenceByFile[filename]
	if !known {
		return nil, false
	}
	columns := make([]string, 0, len(fields))
	for field := range fields {
		columns = append(columns, field)
	}
	return columns, true
}
