#!/usr/bin/env python3
"""Regenerate VALIDATOR_RULES.md from the code.

The previous version of this document was maintained by hand and drifted: it
described validators that no longer exist and codes that were never emitted.
Deriving it from the source means it cannot say something the validator does
not do.

    python3 scripts/gen_validator_rules.py > VALIDATOR_RULES.md
"""

import os
import re
import subprocess
import sys
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "scripts"))
import scope_audit  # noqa: E402

CATEGORIES = [
    ("validator/core/", "Core", "File structure, field types and required fields."),
    ("validator/entity/", "Entity", "Properties and constraints of a single record."),
    ("validator/relationship/", "Relationship", "References between files."),
    ("validator/business/", "Business logic", "Operational consistency across the feed."),
    ("validator/accessibility/", "Accessibility", "Pathways and levels."),
    ("validator/fare/", "Fare", "Fare rules and attributes."),
    ("validator/meta/", "Meta", "Feed metadata."),
    ("", "Other", "Emitted outside the validator packages."),
]


def validator_doc(path):
    """Return the one-line purpose from the validator type's doc comment."""
    text = open(os.path.join(ROOT, path), encoding="utf-8").read()
    m = re.search(r"((?:^//[^\n]*\n)+)type \w+Validator struct", text, re.M)
    if not m:
        return ""
    lines = [line[2:].strip() for line in m.group(1).strip().split("\n")]
    # The first sentence is the purpose; the rest is rationale.
    purpose = " ".join(lines)
    end = purpose.find(". ")
    return purpose if end < 0 else purpose[: end + 1]


def main():
    out = subprocess.run(
        [sys.executable, os.path.join(ROOT, "scripts", "code_map.py"), "--by-file"],
        capture_output=True, text=True, check=True,
    ).stdout

    by_file = defaultdict(list)
    current = None
    for line in out.split("\n"):
        if not line.strip():
            continue
        if not line.startswith("    "):
            current = line.split("  (")[0]
        else:
            by_file[current].append(line.strip())

    ours = scope_audit.scan_repo()
    canon = scope_audit.scrape()

    print("# Validator rules")
    print()
    print("Generated by `scripts/gen_validator_rules.py`. Do not edit by hand.")
    print()
    print("Each validator below is listed with the notice codes it can emit and the")
    print("severity of each. A code marked **canonical** is defined by the")
    print("[Canonical GTFS Schedule Validator](https://gtfs-validator.mobilitydata.org/rules.html)")
    print("and matches its severity; the rest are ours, and by policy none of them is")
    print("ERROR — a code MobilityData does not define is our opinion, and an opinion")
    print("should not fail someone's feed.")
    print()
    print(f"{len(ours)} codes, {sum(1 for c in ours if c in canon)} of them canonical.")
    print()

    assigned = set()
    for prefix, title, blurb in CATEGORIES:
        files = sorted(
            f for f in by_file
            if f not in assigned and (f.startswith(prefix) if prefix else True)
        )
        if not files:
            continue
        assigned |= set(files)

        print(f"## {title}")
        print()
        print(blurb)
        print()
        for path in files:
            name = os.path.basename(path)
            print(f"### `{name}`")
            doc = validator_doc(path)
            if doc:
                print()
                print(doc)
            print()
            print("| code | severity | |")
            print("|---|---|---|")
            for code in by_file[path]:
                severity = ours.get(code, "")
                mark = "canonical" if code in canon else ""
                print(f"| `{code}` | {severity} | {mark} |")
            print()


if __name__ == "__main__":
    main()
