#!/usr/bin/env python3
"""Generate the field table from the GTFS Schedule reference.

Which fields a file has, and whether each is required, recommended or
optional, are facts about the spec rather than judgements about a feed. Kept by
hand they drift: `missing_recommended_field` was reporting three fields the
spec marks Optional, which looked like canonical coverage and was our own
opinion under a canonical code's name. Deriving the table means the spec is the
only place that answers those questions.

    python3 scripts/gen_field_presence.py            # summary
    python3 scripts/gen_field_presence.py --write    # rewrite the Go table
    python3 scripts/gen_field_presence.py --refresh  # re-fetch the reference

The reference is cached at docs/validation-scope/gtfs-reference.md so the
upstream repository is not hit on every run.
"""

import argparse
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CACHE = os.path.join(ROOT, "docs", "validation-scope", "gtfs-reference.md")
TARGET = os.path.join(ROOT, "schema", "field_presence.go")
SOURCE_URL = (
    "https://raw.githubusercontent.com/google/transit/master/gtfs/spec/en/reference.md"
)

# The spec's Presence column, reduced to what a validator can act on.
#
# Conditionally Required and Conditionally Forbidden are deliberately their own
# value rather than being folded into Required or Optional: whether they apply
# depends on the rest of the feed, so no generic check can decide them and each
# belongs to a rule that knows the condition. Collapsing them either way is how
# a generic validator starts reporting things the spec permits.
PRESENCE = {
    "Required": "PresenceRequired",
    "Recommended": "PresenceRecommended",
    "Optional": "PresenceOptional",
    "Conditionally Required": "PresenceConditionallyRequired",
    "Conditionally Forbidden": "PresenceConditionallyForbidden",
}


def load(refresh=False):
    if refresh or not os.path.exists(CACHE):
        import urllib.request

        print(f"fetching {SOURCE_URL} ...", file=sys.stderr)
        with urllib.request.urlopen(SOURCE_URL) as response:
            text = response.read().decode("utf-8")
        os.makedirs(os.path.dirname(CACHE), exist_ok=True)
        with open(CACHE, "w", encoding="utf-8") as handle:
            handle.write(text)
        return text
    return open(CACHE, encoding="utf-8").read()


def parse(text, empty_allowed=None):
    """Return {filename: [(field, presence)]} in the reference's own order.

    empty_allowed, if given, is filled with the fields whose value list offers
    "empty" as a meaningful choice.
    """
    files = {}
    current = None
    if empty_allowed is None:
        empty_allowed = {}

    for line in text.split("\n"):
        heading = re.match(r"^#+\s+([a-z_]+\.(?:txt|geojson))\s*$", line.strip())
        if heading:
            current = heading.group(1)
            files.setdefault(current, [])
            continue
        if current is None:
            continue
        # A new section that is not a file ends the current file's table.
        if line.startswith("#") and not heading:
            current = None
            continue

        row = re.match(r"^\|\s*`([a-z_0-9]+)`\s*\|([^|]*)\|([^|]*)\|(.*)$", line)
        if not row:
            continue

        field, presence, description = row.group(1), row.group(3), row.group(4)
        # A handful of Required fields list "empty" among their valid values —
        # fare_attributes.transfers empty means unlimited, transfers.transfer_type
        # empty means a recommended transfer point. Required there means the
        # column must exist, not that every row must fill it, so a blank is not
        # a defect. Detected from the value list's own "empty - " form, which is
        # what distinguishes it from prose mentioning some other field's blank.
        if presence.strip().lstrip("*_`").startswith("Required") and re.search(
            r"\bempty\s*-\s", description
        ):
            empty_allowed.setdefault(current, []).append(field)
        # The column is written with emphasis on the stronger values.
        presence = re.sub(r"[*_`]", "", presence).strip()
        for label in sorted(PRESENCE, key=len, reverse=True):
            if presence.startswith(label):
                files[current].append((field, PRESENCE[label]))
                break
        else:
            print(f"  ? unknown presence {presence!r} for {current}.{field}", file=sys.stderr)

    return {name: fields for name, fields in files.items() if fields}


def render(files, empty_allowed):
    out = [
        "package schema",
        "",
        "// Code generated by scripts/gen_field_presence.py. DO NOT EDIT.",
        "//",
        "// Source: https://github.com/google/transit, gtfs/spec/en/reference.md",
        "//",
        "// Which fields a file may carry, and whether the spec requires,",
        "// recommends or merely permits each one. Generated because these are",
        "// facts about the specification rather than judgements about a feed:",
        "// kept by hand they drift, and a validator that reports a field the",
        "// spec calls Optional is stating an opinion under a canonical code's",
        "// name.",
        "",
        "// FieldPresence is the spec's Presence column.",
        "type FieldPresence int",
        "",
        "const (",
        "\tPresenceRequired FieldPresence = iota",
        "\tPresenceRecommended",
        "\tPresenceOptional",
        "\t// PresenceConditionallyRequired and PresenceConditionallyForbidden",
        "\t// depend on the rest of the feed, so no generic check can decide",
        "\t// them. Each belongs to a rule that knows the condition.",
        "\tPresenceConditionallyRequired",
        "\tPresenceConditionallyForbidden",
        ")",
        "",
        "// fieldPresenceByFile maps each file to its fields and their presence.",
        "var fieldPresenceByFile = map[string]map[string]FieldPresence{",
    ]

    for name in sorted(files):
        out.append(f'\t{name!r}: {{'.replace("'", '"'))
        for field, presence in files[name]:
            out.append(f'\t\t"{field}": {presence},')
        out.append("\t},")

    out += [
        "}",
        "",
        "// FieldsWithPresence returns the fields of a file at a given presence,",
        "// and whether the file is one the spec describes at all.",
        "func FieldsWithPresence(filename string, presence FieldPresence) ([]string, bool) {",
        "\tfields, known := fieldPresenceByFile[filename]",
        "\tif !known {",
        "\t\treturn nil, false",
        "\t}",
        "\tmatching := make([]string, 0, len(fields))",
        "\tfor field, actual := range fields {",
        "\t\tif actual == presence {",
        "\t\t\tmatching = append(matching, field)",
        "\t\t}",
        "\t}",
        "\treturn matching, true",
        "}",
        "",
        "// emptyIsMeaningful lists the Required fields whose value list offers",
        "// \"empty\" as a choice. Required there means the column must exist, not",
        "// that every row must fill it, so a blank is not a missing value.",
        "var emptyIsMeaningful = map[string]map[string]bool{",
    ] + [
        line
        for name in sorted(empty_allowed)
        for line in [f'\t"{name}": {{']
        + [f'\t\t"{f}": true,' for f in empty_allowed[name]]
        + ["\t},"]
    ] + [
        "}",
        "",
        "// EmptyIsMeaningful reports whether a blank in this field is a value",
        "// rather than an omission.",
        "func EmptyIsMeaningful(filename string, field string) bool {",
        "\treturn emptyIsMeaningful[filename][field]",
        "}",
        "",
        "// KnownColumns returns every column the spec defines for a file, and",
        "// whether the file is described at all.",
        "func KnownColumns(filename string) ([]string, bool) {",
        "\tfields, known := fieldPresenceByFile[filename]",
        "\tif !known {",
        "\t\treturn nil, false",
        "\t}",
        "\tcolumns := make([]string, 0, len(fields))",
        "\tfor field := range fields {",
        "\t\tcolumns = append(columns, field)",
        "\t}",
        "\treturn columns, true",
        "}",
        "",
    ]
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true", help="rewrite the Go table")
    ap.add_argument("--refresh", action="store_true", help="re-fetch the reference")
    args = ap.parse_args()

    empty_allowed = {}
    files = parse(load(args.refresh), empty_allowed)

    counts = {}
    for fields in files.values():
        for _, presence in fields:
            counts[presence] = counts.get(presence, 0) + 1

    print(f"{len(files)} files, {sum(len(f) for f in files.values())} fields")
    for presence, count in sorted(counts.items()):
        print(f"  {presence:32} {count}")

    print("required fields where empty is a value, not an omission:")
    for name in sorted(empty_allowed):
        for field in empty_allowed[name]:
            print(f"  {name}.{field}")

    if args.write:
        with open(TARGET, "w", encoding="utf-8") as handle:
            handle.write(render(files, empty_allowed))
        print(f"\nwrote {TARGET}")


if __name__ == "__main__":
    main()
