#!/usr/bin/env python3
"""Generate notice descriptions from the Canonical GTFS Validator rule registry.

MobilityData publishes a one-line description for every notice code it defines
at https://gtfs-validator.mobilitydata.org/rules.html. This script scrapes that
page and writes notice_descriptions_mobilitydata.go, so the descriptions in our
reports are the upstream wording rather than text generated from the code name.

Usage:
    python3 scripts/gen_notice_descriptions.py [--cache rules.html]

Codes we emit that MobilityData does not define get no description here; the
Go fallback handles those.
"""

import argparse
import html
import os
import re
import sys
import urllib.request

RULES_URL = "https://gtfs-validator.mobilitydata.org/rules.html"
OUTPUT = os.path.join(os.path.dirname(__file__), "..", "notice_descriptions_mobilitydata.go")

# Each rule is a table row: an anchor carrying the code, then a cell holding a
# font-bold div with the one-line summary, followed by a longer explanation.
# The explanation may run to several paragraphs and example tables; only its
# first paragraph is taken.
ROW = re.compile(
    r'id="(?P<code>[a-z_0-9]+)-table".*?'
    r'<td><div class="font-bold">(?P<short>.*?)</div>'
    r'(?P<long>.*?)</td>',
    re.DOTALL,
)

FIRST_PARAGRAPH = re.compile(r"<p>(.*?)</p>", re.DOTALL)


def fetch(cache):
    if cache and os.path.exists(cache):
        with open(cache, encoding="utf-8") as fh:
            return fh.read()
    with urllib.request.urlopen(RULES_URL) as resp:
        body = resp.read().decode("utf-8")
    if cache:
        with open(cache, "w", encoding="utf-8") as fh:
            fh.write(body)
    return body


def clean(fragment):
    """Reduce an HTML description fragment to a single plain-text sentence."""
    text = re.sub(r"<!--.*?-->", " ", fragment, flags=re.DOTALL)
    text = re.sub(r"<[^>]+>", " ", text)
    text = html.unescape(text)
    text = text.replace("“", '"').replace("”", '"')
    text = text.replace("‘", "'").replace("’", "'")
    text = re.sub(r"\s+", " ", text).strip()
    return text


def parse(body):
    descriptions = {}
    for match in ROW.finditer(body):
        short = clean(match.group("short"))

        detail = ""
        paragraph = FIRST_PARAGRAPH.search(match.group("long"))
        if paragraph:
            detail = clean(paragraph.group(1))

        descriptions[match.group("code")] = join(short, detail)
    return {code: text for code, text in descriptions.items() if text}


def join(short, detail):
    """Combine the summary with its explanation, avoiding a restatement."""
    if not detail:
        return short
    if not short:
        return detail
    if detail.lower().startswith(short.lower().rstrip(".")):
        return detail
    if short.rstrip(".").lower() in detail.lower():
        return detail
    return short.rstrip() + " " + detail


def render(descriptions):
    lines = [
        "// Code generated by scripts/gen_notice_descriptions.py. DO NOT EDIT.",
        "//",
        "// Source: " + RULES_URL,
        "//",
        "// Descriptions for the notice codes defined by the Canonical GTFS Schedule",
        "// Validator. Codes we emit that MobilityData does not define are absent here",
        "// and fall back to a description derived from the code name.",
        "",
        "package gtfsvalidator",
        "",
        "var mobilityDataDescriptions = map[string]string{",
    ]
    for code in sorted(descriptions):
        lines.append("\t%s: %s," % (go_quote(code), go_quote(descriptions[code])))
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def go_quote(value):
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--cache", help="read/write the rules page here instead of refetching")
    args = parser.parse_args()

    descriptions = parse(fetch(args.cache))
    if len(descriptions) < 150:
        sys.exit("only parsed %d rules; the page layout probably changed" % len(descriptions))

    with open(OUTPUT, "w", encoding="utf-8") as fh:
        fh.write(render(descriptions))
    print("wrote %d descriptions to %s" % (len(descriptions), os.path.normpath(OUTPUT)))


if __name__ == "__main__":
    main()
